%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% Coordination number
%
% Reads csv file generated by Paraview of force chain data. The cohesive
%   force should not be included in these files.
%
% This is not a function, just a script to copy and paste into the matlab
%   terminal.
%
% Inputs: 'filename', number of final timestep for force chains
%
% Outputs: creates csv files for particles and includes the 
%   coordination number and the particle center locations
%
% September 12, 2016
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

clear all; close all;

% Make sure to change below if looking at a mixing region problem
filename='granular_flow_lube_fc';
finaltime=9999;
box_size=5;

cd('/home/zack/Documents/csv_data_files/')

% Set up headers for saving files and empty array for saving the averages
headers={'Position:0','Position:1','Coordination'};
average_counts=[];

for timestep=1:finaltime,
    timestep
    force_data=csvread([filename,'.',num2str(timestep),'.csv'],1,0);
    % Columns read in are: f_normal f_tangential f_magnitude X Y Z
    % There are 2 rows per contact.
    all_endpoints=force_data(:,4:5);    % Just grab the x,y coordinates
    
    % Process to eliminate duplicate contacts from processor issues
    a=all_endpoints(1:2:length(all_endpoints),:);   % First particles
    b=all_endpoints(2:2:length(all_endpoints),:);   % Second particles
    c=cat(2,a,b);                                   % First Second
    d=cat(2,b,a);                                   % Second First
    f=cat(1,c,d);                                   % Stacks c & d
       
    % Removes duplicate combinations: 1 -> 2 = 2 -> 1
    g=unique(f,'rows');     
    % Take only the first column (1 endpoint)
    endpoints=g(:,1:2);                 
    
    % Get the unique rows, the indices of each unique row, and the indices 
    % of the unique values in the original vector
    [unique_endpoints, ia, ic]=unique(endpoints,'rows');
    counts=transpose(histcounts(ic,length(unique_endpoints)));
    
    % Write coordinates and coordination number for all particles
    data=cat(2,unique_endpoints,counts);
    csvwrite_with_headers([filename,'_coordination.',num2str(timestep), ...
        '.csv'],data,headers,0,0);
    
    % UNCOMMENT ONLY IF LOOKING AT MIXING REGION PROBLEMS
    %data(data(:,1) < 64.5,:)=[];
    %data(data(:,1) > 191.5,:)=[];
    % Keeps average coordination number for all timesteps
    average_counts=cat(1,average_counts,mean(data(:,3)));
    
end

% Write average coordination number values
% cd('/home/zack/Documents/csv_data_files/')
csvwrite(['ave_coord_',filename,'.csv'],average_counts,0,0);

% Plots average coordination number
plot(time,average_counts)
xlabel('Time (s)')
ylabel('Coordination number')

cd('/home/zack/Documents/matlab_scripts/')

